name: build docker image

on:
  push:
    paths:
      - ml/*

jobs: 
  build-deploy-ml:
    runs-on: python:3.8-slim-buster
  
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: build and push ml image
        uses: docker/build-push-action@v4
        with:
          context: ml/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml 

on:
  push:
    paths:
      - server/*

jobs: 
  build-deploy-server:
    runs-on: python:3.8-slim-buster
  
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: build and push server image
        uses: docker/build-push-action@v4
        with:
          context: server/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/server 