apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
      - name: server
        image: philipedc/server:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 32211
        volumeMounts:
        - name: rules
          mountPath: /app/rules
      initContainers:
      - name: ml
        image: philipedc/ml:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: rules
          mountPath: /app/rules
        env:
        - name: DATASET_URL
          value: "https://homepages.dcc.ufmg.br/~cunha/hosted/cloudcomp-2023s2-datasets/2023_spotify_ds1.csv"
      volumes:
      - name: rules
        persistentVolumeClaim:
          claimName: project2-pvc-philipecunha
