apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: philipedc/server:latest
        ports:
          - containerPort: 32211
        volumeMounts:
        - name: project2-pv-philipecunha
          mountPath: /app/rules
      initContainers:
      - name: ml
        image: philipedc/ml:latest
        restartPolicy: OnFailure
        volumeMounts:
        - name: project2-pv-philipecunha
          mountPath: /app/rules
      volumes:
      - name: project2-pv-philipecunha
        persistentVolumeClaim:
          claimName: project2-pv-philipecunha