apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: philipecunha
  name: project2-pvc-philipecunha
spec:
  volumeName: project2-pv-philipecunha 
  accessModes:
    - ReadWriteMany 
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: local
