name: build docker image ml

on:
  push:
    paths:
      - TP2/ml/*

jobs:
  build-deploy-ml:
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: ${{ github.run_number }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push ml image
        uses: docker/build-push-action@v4
        with:
          context: TP2/ml/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ml:${{ env.IMAGE_VERSION }}
